### ISSUE TITLE
AttributeError error when importing localgraphclustering

### ISSUE THREAD

**Issue by hyhzxhy** [kfoynt/LocalGraphClustering#110]
Issue 96 may have  similar problem as me. 
(https://github.com/kfoynt/LocalGraphClustering/issues/96)
But there was little information so I will provide some details here.

I am running python3.6 in jupyter notebook, with macOS 10.14.5. The error message is shown below:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-3-8da92a9ab2a6> in <module>
----> 1 import localgraphclustering as lgc

/anaconda3/lib/python3.6/site-packages/localgraphclustering/__init__.py in <module>
----> 1 from .GraphLocal import GraphLocal
      2 from .GraphDrawing import GraphDrawing
      3 from .fiedler import fiedler, fiedler_local
      4 from .approximate_PageRank import approximate_PageRank
      5 from .approximate_PageRank_weighted import approximate_PageRank_weighted

/anaconda3/lib/python3.6/site-packages/localgraphclustering/GraphLocal.py in <module>
      8 import warnings
      9 import collections as cole
---> 10 from .cpp import *
     11 import random
     12 

/anaconda3/lib/python3.6/site-packages/localgraphclustering/cpp/__init__.py in <module>
     41 from .MQI_cpp import *
     42 from .proxl1PRaccel import *
---> 43 from .proxl1PRrand_cpp import *
     44 from .SimpleLocal_cpp import *
     45 from .sweepcut_cpp import *

/anaconda3/lib/python3.6/site-packages/localgraphclustering/cpp/proxl1PRrand_cpp.py in <module>
     50 
     51 _graphlib_funs_proxl1PRrand64 = _setup_proxl1PRrand_args(
---> 52     'int64','int64', _graphlib.proxl1PRrand64)
     53 _graphlib_funs_proxl1PRrand32 = _setup_proxl1PRrand_args(
     54     'uint32','uint32', _graphlib.proxl1PRrand32)

/anaconda3/lib/python3.6/ctypes/__init__.py in __getattr__(self, name)
    359         if name.startswith('__') and name.endswith('__'):
    360             raise AttributeError(name)
--> 361         func = self.__getitem__(name)
    362         setattr(self, name, func)
    363         return func

/anaconda3/lib/python3.6/ctypes/__init__.py in __getitem__(self, name_or_ordinal)
    364 
    365     def __getitem__(self, name_or_ordinal):
--> 366         func = self._FuncPtr((name_or_ordinal, self))
    367         if not isinstance(name_or_ordinal, int):
    368             func.__name__ = name_or_ordinal

AttributeError: dlsym(0x7fec89d9ade0, proxl1PRrand64): symbol not found
```

It seems to me that something goes wrong with the c library. But I'm not familiar with this. Could anyone give some help? Thanks in advance.

**Comment by dgleich** [comment]
Do you have a C++ compiler installed? How did you install the package?

**Comment by hyhzxhy** [comment]
> Do you have a C++ compiler installed? How did you install the package?

I think I have installed gcc, some information about it is shown below : 

```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

And i installed the package by : 

`pip3 install localgraphclustering`

**Comment by MengLiuPurdue** [comment]
> > Do you have a C++ compiler installed? How did you install the package?
> 
> I think I have installed gcc, some information about it is shown below :
> 
> ```
> Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
> Apple LLVM version 10.0.1 (clang-1001.0.46.4)
> Target: x86_64-apple-darwin18.6.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin
> ```
> 
> And i installed the package by :
> 
> `pip install localgraphclustering`

Can you try to run 'bin/createGraphLibFile.sh' from the package repository and see if that can finish successfully?

**Comment by hyhzxhy** [comment]
> > > Do you have a C++ compiler installed? How did you install the package?
> > 
> > 
> > I think I have installed gcc, some information about it is shown below :
> > ```
> > Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
> > Apple LLVM version 10.0.1 (clang-1001.0.46.4)
> > Target: x86_64-apple-darwin18.6.0
> > Thread model: posix
> > InstalledDir: /Library/Developer/CommandLineTools/usr/bin
> > ```
> > 
> > 
> > And i installed the package by :
> > `pip install localgraphclustering`
> 
> Can you try to run 'bin/createGraphLibFile.sh' from the package repository and see if that can finish successfully?

No, it doesn't work.
However, I clone the repo and try to use :
`python setup.py install`
instead, and it works. I can now import localgraphclustering in terminal, though jupyter notebook still fails.

While using this method, I encountered another problem :
```
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead
```

I fixed it by changing the code in ncpplots.py.

Next I may try to do something with my jupyter notebook...
