### ISSUE TITLE
Pick clusters based on local minimum conductance

### ISSUE THREAD

**Issue by HereComesWalrus** [kfoynt/LocalGraphClustering#113]
Is there any way to pick clusters based on local minimum conductance?

**Comment by kfoynt** [comment]
Could you elaborate a little about what you mean with "local minimum conductance"? For example, the MQI algorithm that is implemented in LGC in flow_clustering.py. MQI minimizes conductance exactly within the given set of nodes (the given set of nodes has to have volume less than the volume of the graph).

**Comment by HereComesWalrus** [comment]
I am using spectral_clustering, method="nibble".

I have 20 twitter users (graph ids) which I have isolated as "influencers" and want to calculate clusters around each one of them.

My graph has around 2 Million nodes.

I want to decide what is the best vol, phi as an input, and am printing the conductance of the spectral_clustering calls output (size of the cluster as x, conductance as y) but cant seem to make a good decision, as my results afterwards are being bad.

**Comment by kfoynt** [comment]
You could use MQI to further improve the conductance of the output of nibble. An example code about how to call MQI is given in Ln [9] in https://github.com/kfoynt/LocalGraphClustering/blob/master/notebooks/examples.ipynb.  

Another algorithm for improving the conductance of the output of Nibble is SimpleLocal. An example code about how to call SimpleLocal is given in Ln [10] in the same link above. 

Regarding nibble, theory mentions that you should set vol proportional to the volume of your target cluster. For phi, theory says that it should be set similar to the conductance of your target cluster. 

However, I am guessing that you do not have this information for your target cluster. You could implement a binary search on phi. Unfortunately, we have not implemented binary search for Nibble yet. 

In any case, I totally recommend to use the output of Nibble as input to MQI and SimpleLocal. Let us know if that does not work out either. 

Also, could you give some more info about what "bad" means here? How do you measure "goodness" of a cluster?
