### ISSUE TITLE
the range of the random number generator in proxl1PRrand is too small

### ISSUE THREAD

**Issue by MengLiuPurdue** [kfoynt/LocalGraphClustering#114]
It looks like the random number generator in proxl1PRrand can only generate at most 32767 numbers, which is too small for large graphs

**Comment by kfoynt** [comment]
Hm, interesting!! Why is that? Can you quickly fix this?

**Comment by MengLiuPurdue** [comment]
Because it's generating a 16 bit random number...

**Comment by kfoynt** [comment]
ok if you know how to fix this, can you modify it?

**Comment by MengLiuPurdue** [comment]
I plan to use a library in c++11 as explained here https://stackoverflow.com/questions/21096015/how-to-generate-64-bit-random-numbers or @dgleich you have a better way to do this?

**Comment by dgleich** [comment]
I've had bad luck with the C++ random number generators having issues compiling on multiple platforms. But that was about 10 years ago right when they introduced them. I would hope it's been addressed by now. But you might just check that these all compile nicely on windows, mac, and linux...
