### ISSUE TITLE
ACL: Degree normalized pagerank for sweepcut

### ISSUE THREAD

**Issue by ednaMode1985** [kfoynt/LocalGraphClustering#116]
In reading through the notebooks, I notice that https://github.com/kfoynt/LocalGraphClustering/blob/master/notebooks/examples.ipynb has examples of ACL where the output of approximate personalized page rank is input directly into sweep_cut, while the paper (http://www.leonidzhukov.net/hse/2015/networks/papers/andersen06localgraph.pdf, Section 2.4 , and others) suggests using degree normalized pagerank. That seemed like a discrepancy to me, unless I am missing something. Hoping to get your comment/feedback on this.

**Comment by dgleich** [comment]
The ACL routine automatically normalizes the output so that it's appropriate for this usage. If you want raw ACL, you need to set normalize=False

**Comment by kfoynt** [comment]
Hey, there is a parameter in approximatePageRank that is called normalize that if True then the output of ACL is divided by the degree. This parameter is set by default to True.

**Comment by kfoynt** [comment]
Alright, David replied already!

**Comment by ednaMode1985** [comment]
Got it, thank you!
