### ISSUE TITLE
OSError: [WinError 126]

### ISSUE THREAD

**Issue by golabiyebahal** [kfoynt/LocalGraphClustering#124]
Does this package work with Windows10? I installed it on Python 3.7.4 (with pip3). When tried to import it on Jupytor got this error: 

OSError                                   Traceback (most recent call last)
...

~\Anaconda3\envs\newenvt\lib\ctypes\__init__.py in LoadLibrary(self, name)
    440 
    441     def LoadLibrary(self, name):
--> 442         return self._dlltype(name)
    443 
    444 cdll = LibraryLoader(CDLL)

~\Anaconda3\envs\newenvt\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: [WinError 126] The specified module could not be found

**Comment by kfoynt** [comment]
Hey, unfortunately, it does not work on Windows.

**Comment by golabiyebahal** [comment]
What operating system can I use for it?

**Comment by kfoynt** [comment]
Linux, OSX.

**Comment by golabiyebahal** [comment]
I tried it on a Linux server (Ubuntu 16.04) and installed the package on python 3.6 (via pip). I have a C++ compiler. When I import the package I got this error:
![image](https://user-images.githubusercontent.com/54515158/91203016-da125d00-e6bf-11ea-8e8b-213be756f9f5.png)

**Comment by kfoynt** [comment]
I would recommend installing by downloading the package, then go the main folder and type in the terminal "python setup.py install".

**Comment by golabiyebahal** [comment]
It works. Thanks!
