### ISSUE TITLE
 module 'localgraphclustering' has no attribute 'GraphLocal'

### ISSUE THREAD

**Issue by ebimor** [kfoynt/LocalGraphClustering#47]
Hello,

I am trying to run the examples.ipynb in Jupyter, however I receive this error after executing the second cell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-ef637189f002> in <module>()
      1 # Read graph. This also supports gml format.
----> 2 g = lgc.GraphLocal('datasets/JohnsHopkins.graphml','graphml')
      3 
      4 # To get a quick look at the list of methods and attributes for the graph object 'g' you can type 'g.' + tab
      5 # and scroll up or down.

AttributeError: module 'localgraphclustering' has no attribute 'GraphLocal'

**Comment by kfoynt** [comment]
Hi, 

Did you install the package successfully? Did you install the package for the version of Python that is being used by Jupyter?
