### ISSUE TITLE
Small code update for as_matrix() to .values 

### ISSUE THREAD

**Issue by dgleich** [kfoynt/LocalGraphClustering#48]
When I ran this using some updated libraries, I got the warning:

```
/homes/dgleich/.local/lib/python3.5/site-packages/localgraphclustering/ncpplots.py:18: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  xs = df[group].as_matrix().copy()
```

We should probably fix that to use .values !

**Comment by 17120392** [comment]
I think you can update your pandas. It will be ok!(I have met with this problem, and have solved it)

**Comment by dgleich** [comment]
This was fixed recently.

**Comment by MengLiuPurdue** [comment]
> I meet the same problem,can you tell me how this was fixed? Thanks!

Are you using the latest version of this package? (use git clone from github) I think we have already changed as_matrix to values.
