### ISSUE TITLE
Pkg.add(PyCall) should be Pkg.add("PyCall")

### ISSUE THREAD

**Issue by arbenson** [kfoynt/LocalGraphClustering#52]
For the Julia setup in the README,
Pkg.add(PyCall) should be Pkg.add("PyCall")

**Comment by kfoynt** [comment]
Thanks. We will fix this asap.

**Comment by arbenson** [comment]
Also, for Step 4 of the "Import from Julia" section, you need to be using PyCall. So in the README this should be 

`using PyPlot
using PyCall
@pyimport localgraphclustering`

Instead of the current

`using PyPlot

@pyimport localgraphclustering`

Thanks!
