### ISSUE TITLE
Compute conductance in C++

### ISSUE THREAD

**Issue by dgleich** [kfoynt/LocalGraphClustering#57]
@MengLiuPurdue We should have a routine to compute conductance and conductance for weighted graphs in C++. These will be much faster than our current ones :)

Probably the best thing to do is to write: cut_value and weighted_cut value in C++ that take in an array of vertex ids.

Then we can just change set_scores in GraphLocal to use the C++ code to compute the cut and everything should be faster. At the moment, computing these conductance scores is taking a substantial fraction of the total time of an NCP. (e.g. like 50%...)

**Comment by MengLiuPurdue** [comment]
Ok, will do.
