### ISSUE TITLE
libgraph.dll can not find  in win 10

### ISSUE THREAD

**Issue by lidadreamer** [kfoynt/LocalGraphClustering#60]
when i test the example of the main page, i met the question below
![image](https://user-images.githubusercontent.com/17985259/45399888-78948780-b67c-11e8-98f0-c0de240c283e.png)
thank u

**Comment by MengLiuPurdue** [comment]
This package is not working on windows currently. I can try to make it work sometime in the future.

**Comment by lidadreamer** [comment]
thank u ,and maybe make docker image for this could help lol
